# Generated by Django 5.1.7 on 2025-04-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_picture_description_picture_sneakers'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sneakers',
            name='description',
            field=models.TextField(default='–', max_length=300),
            preserve_default=False,
        ),
    ]
