# Generated by Django 5.1.7 on 2025-04-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_picture_is_public_alter_sneakers_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='is_public',
        ),
        migrations.AddField(
            model_name='sneakers',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
